/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.pillageandplunder.chickenfooter;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int game1=0x7f050000;
        public static final int new_player_name=0x7f050001;
        public static final int new_score_confirm=0x7f050005;
        public static final int new_score_value=0x7f050004;
        public static final int player_name1=0x7f050002;
        public static final int player_score1=0x7f050003;
        public static final int score_value1=0x7f050007;
        public static final int scores_player_name=0x7f050006;
    }
    public static final class layout {
        public static final int games_row=0x7f030000;
        public static final int main=0x7f030001;
        public static final int player_new=0x7f030002;
        public static final int players=0x7f030003;
        public static final int players_row=0x7f030004;
        public static final int score_new=0x7f030005;
        public static final int scores=0x7f030006;
        public static final int scores_row=0x7f030007;
    }
    public static final class string {
        public static final int add_score=0x7f040008;
        public static final int app_name=0x7f04000a;
        public static final int confirm=0x7f040007;
        public static final int delete_game=0x7f04000b;
        public static final int done=0x7f040009;
        public static final int name=0x7f040005;
        public static final int new_game=0x7f040001;
        public static final int new_player=0x7f040003;
        public static final int no_games=0x7f040000;
        public static final int no_players=0x7f040002;
        public static final int no_scores=0x7f040004;
        public static final int score=0x7f040006;
    }
}
